export const PERMISSIONS = [
  { code: "user.manage", name: "Quản lý tài khoản", description: "Tạo, khóa và cập nhật tài khoản người dùng." },
  { code: "role.manage", name: "Quản lý vai trò và quyền", description: "Gán vai trò, cấp thêm hoặc thu hồi quyền riêng." },
  { code: "student.view", name: "Xem học viên", description: "Xem hồ sơ, danh sách và dữ liệu học tập của học viên." },
  { code: "student.create", name: "Thêm học viên", description: "Tạo hồ sơ học viên và import từ Excel." },
  { code: "student.update", name: "Cập nhật học viên", description: "Sửa hồ sơ, phụ huynh và tài khoản liên kết." },
  { code: "student.delete", name: "Xóa học viên", description: "Xóa hồ sơ học viên khỏi hệ thống." },
  { code: "parent.view", name: "Xem phụ huynh", description: "Xem danh sách và thông tin phụ huynh." },
  { code: "parent.create", name: "Thêm phụ huynh", description: "Tạo hồ sơ phụ huynh." },
  { code: "parent.update", name: "Cập nhật phụ huynh", description: "Sửa thông tin phụ huynh." },
  { code: "parent.delete", name: "Xóa phụ huynh", description: "Xóa hồ sơ phụ huynh." },
  { code: "class.view", name: "Xem lớp học", description: "Xem danh sách, chi tiết lớp và học viên trong lớp." },
  { code: "class.create", name: "Tạo lớp học", description: "Tạo lớp học, mã lớp và cấu hình học phí." },
  { code: "class.update", name: "Cập nhật lớp học", description: "Sửa thông tin lớp, học phí, học viên và lịch học." },
  { code: "class.delete", name: "Xóa lớp học", description: "Xóa lớp học và dữ liệu vận hành liên quan." },
  { code: "class.assign_teacher", name: "Phân công giáo viên", description: "Gán hoặc gỡ giáo viên phụ trách lớp." },
  { code: "schedule.view", name: "Xem lịch học", description: "Xem lịch cố định và lịch buổi học." },
  { code: "schedule.manage", name: "Quản lý lịch học", description: "Tạo, sửa, hủy lịch học và buổi học." },
  { code: "session.view", name: "Xem buổi học", description: "Xem nội dung buổi học, phòng học và giáo viên thực tế." },
  { code: "session.manage", name: "Quản lý buổi học", description: "Tạo, hoàn tất, hủy và cập nhật buổi học." },
  { code: "attendance.view", name: "Xem điểm danh học viên", description: "Xem chuyên cần của học viên." },
  { code: "attendance.manage", name: "Quản lý điểm danh học viên", description: "Điểm danh, sửa trạng thái và ghi chú học viên." },
  { code: "comment.view", name: "Xem nhận xét", description: "Xem nhận xét học tập của học viên." },
  { code: "comment.manage", name: "Quản lý nhận xét", description: "Tạo và cập nhật nhận xét học tập." },
  { code: "exam.view", name: "Xem bài kiểm tra", description: "Xem bài kiểm tra và bảng điểm." },
  { code: "exam.manage", name: "Quản lý bài kiểm tra", description: "Tạo bài kiểm tra, nhập điểm và import điểm." },
  { code: "score.view", name: "Xem điểm số", description: "Xem điểm theo học viên và lớp." },
  { code: "score.manage", name: "Quản lý điểm số", description: "Nhập, sửa và import điểm số." },
  { code: "tuition.view", name: "Xem học phí", description: "Xem khoản phải thu, thanh toán và công nợ." },
  { code: "tuition.manage", name: "Quản lý học phí", description: "Tạo khoản phải thu và điều chỉnh thông tin học phí." },
  { code: "payment.view", name: "Xem thanh toán", description: "Xem lịch sử thu tiền." },
  { code: "payment.manage", name: "Quản lý thanh toán", description: "Ghi nhận thanh toán học phí." },
  { code: "salary.view", name: "Xem lương", description: "Xem quy tắc lương, bảng lương và chi tiết chi trả." },
  { code: "salary.manage", name: "Quản lý lương", description: "Tạo bảng lương, điều chỉnh và xác nhận chi trả." },
  { code: "staff_attendance.view", name: "Xem chấm công nhân sự", description: "Xem ngày công, giờ làm và trạng thái chấm công nhân sự." },
  { code: "staff_attendance.manage", name: "Quản lý chấm công nhân sự", description: "Tạo, sửa, xóa và xác nhận chấm công nhân sự." },
  { code: "report.learning.view", name: "Báo cáo học tập", description: "Xem báo cáo học viên, lớp, điểm danh, nhận xét và điểm số." },
  { code: "report.finance.view", name: "Báo cáo tài chính", description: "Xem số liệu học phí, thanh toán và công nợ." },
  { code: "report.staff.view", name: "Báo cáo nhân sự", description: "Xem số liệu nhân sự, buổi dạy và ngày công." },
  { code: "audit_log.view", name: "Xem nhật ký thao tác", description: "Xem lịch sử thao tác quan trọng trong hệ thống." },
] as const;

export const ROLES = [
  { code: "admin", name: "Admin / Quản lý", description: "Toàn quyền hệ thống" },
  { code: "teacher_main", name: "Giáo viên chính", description: "Quản lý lớp được phân công" },
  { code: "teacher_assistant", name: "Giáo viên phụ", description: "Hỗ trợ lớp được cấp quyền" },
  { code: "accountant", name: "Kế toán", description: "Học phí, thanh toán, lương và chấm công" },
  { code: "receptionist", name: "Lễ tân", description: "Hỗ trợ vận hành và chăm sóc phụ huynh" },
  { code: "academic", name: "Học vụ", description: "Sắp xếp lớp, lịch học, buổi học và chấm công vận hành" },
  { code: "collaborator", name: "Cộng tác viên", description: "Tác vụ được giao theo phạm vi" },
  { code: "part_time", name: "Nhân viên thời vụ", description: "Tài khoản nhân sự thời vụ theo phân công" },
  { code: "student", name: "Học viên", description: "Xem dữ liệu học tập của chính mình" },
  { code: "parent", name: "Phụ huynh", description: "Xem dữ liệu học tập của học viên liên kết" },
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number]["code"];
export type RoleCode = (typeof ROLES)[number]["code"];

export const ALL_PERMISSION_CODES = PERMISSIONS.map(({ code }) => code);

export const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  admin: [...ALL_PERMISSION_CODES],
  teacher_main: [
    "student.view",
    "student.create",
    "student.update",
    "student.delete",
    "parent.view",
    "class.view",
    "schedule.view",
    "session.view",
    "session.manage",
    "attendance.view",
    "attendance.manage",
    "comment.view",
    "comment.manage",
    "exam.view",
    "exam.manage",
    "score.view",
    "score.manage",
    "report.learning.view",
  ],
  teacher_assistant: [
    "student.view",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
    "comment.view",
    "exam.view",
    "score.view",
  ],
  accountant: [
    "student.view",
    "parent.view",
    "class.view",
    "tuition.view",
    "tuition.manage",
    "payment.view",
    "payment.manage",
    "salary.view",
    "salary.manage",
    "staff_attendance.view",
    "staff_attendance.manage",
    "report.finance.view",
    "report.staff.view",
  ],
  receptionist: [
    "student.view",
    "student.create",
    "student.update",
    "parent.view",
    "parent.create",
    "parent.update",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
  ],
  academic: [
    "student.view",
    "parent.view",
    "class.view",
    "class.create",
    "class.update",
    "class.assign_teacher",
    "schedule.view",
    "schedule.manage",
    "session.view",
    "session.manage",
    "attendance.view",
    "attendance.manage",
    "comment.view",
    "staff_attendance.view",
    "staff_attendance.manage",
    "report.learning.view",
    "report.staff.view",
  ],
  collaborator: ["student.view", "class.view", "schedule.view", "session.view"],
  part_time: ["schedule.view", "session.view"],
  student: [
    "student.view",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
    "comment.view",
    "exam.view",
    "score.view",
  ],
  parent: [
    "student.view",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
    "comment.view",
    "exam.view",
    "score.view",
    "tuition.view",
  ],
};

export function hasPermission(
  permissions: readonly string[],
  permission: PermissionCode,
) {
  return permissions.includes(permission);
}

export function roleLabel(code: string) {
  return ROLES.find((role) => role.code === code)?.name ?? code;
}
