export const PERMISSIONS = [
  { code: "user.manage", name: "Quản lý tài khoản" },
  { code: "role.manage", name: "Quản lý vai trò và quyền" },
  { code: "student.view", name: "Xem học viên" },
  { code: "student.create", name: "Thêm học viên" },
  { code: "student.update", name: "Cập nhật học viên" },
  { code: "student.delete", name: "Xóa học viên" },
  { code: "parent.view", name: "Xem phụ huynh" },
  { code: "parent.create", name: "Thêm phụ huynh" },
  { code: "parent.update", name: "Cập nhật phụ huynh" },
  { code: "parent.delete", name: "Xóa phụ huynh" },
  { code: "class.view", name: "Xem lớp học" },
  { code: "class.create", name: "Tạo lớp học" },
  { code: "class.update", name: "Cập nhật lớp học" },
  { code: "class.delete", name: "Xóa lớp học" },
  { code: "class.assign_teacher", name: "Phân công giáo viên" },
  { code: "schedule.view", name: "Xem lịch học" },
  { code: "schedule.manage", name: "Quản lý lịch học" },
  { code: "session.view", name: "Xem buổi học" },
  { code: "session.manage", name: "Quản lý buổi học" },
  { code: "attendance.view", name: "Xem điểm danh" },
  { code: "attendance.manage", name: "Quản lý điểm danh" },
  { code: "comment.view", name: "Xem nhận xét" },
  { code: "comment.manage", name: "Quản lý nhận xét" },
  { code: "exam.view", name: "Xem bài kiểm tra" },
  { code: "exam.manage", name: "Quản lý bài kiểm tra" },
  { code: "score.view", name: "Xem điểm số" },
  { code: "score.manage", name: "Quản lý điểm số" },
  { code: "tuition.view", name: "Xem học phí" },
  { code: "tuition.manage", name: "Quản lý học phí" },
  { code: "payment.view", name: "Xem thanh toán" },
  { code: "payment.manage", name: "Quản lý thanh toán" },
  { code: "salary.view", name: "Xem lương" },
  { code: "salary.manage", name: "Quản lý lương" },
  { code: "report.learning.view", name: "Báo cáo học tập" },
  { code: "report.finance.view", name: "Báo cáo tài chính" },
  { code: "report.staff.view", name: "Báo cáo nhân sự" },
  { code: "audit_log.view", name: "Xem nhật ký thao tác" },
] as const;

export const ROLES = [
  { code: "admin", name: "Admin / Quản lý", description: "Toàn quyền hệ thống" },
  { code: "teacher_main", name: "Giáo viên chính", description: "Quản lý lớp được phân công" },
  { code: "teacher_assistant", name: "Giáo viên phụ", description: "Hỗ trợ lớp được cấp quyền" },
  { code: "accountant", name: "Kế toán", description: "Học phí, thanh toán và lương" },
  { code: "receptionist", name: "Lễ tân", description: "Hỗ trợ vận hành và chăm sóc phụ huynh" },
  { code: "academic", name: "Học vụ", description: "Sắp xếp lớp, lịch học và buổi học" },
  { code: "collaborator", name: "Cộng tác viên", description: "Tác vụ được giao theo phạm vi" },
  { code: "part_time", name: "Nhân viên thời vụ", description: "Tài khoản nhân sự thời vụ theo phân công" },
  { code: "student", name: "Học viên", description: "Xem dữ liệu học tập của chính mình" },
  { code: "parent", name: "Phụ huynh", description: "Xem dữ liệu học tập của học viên liên kết" },
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number]["code"];
export type RoleCode = (typeof ROLES)[number]["code"];

export const ALL_PERMISSION_CODES = PERMISSIONS.map(({ code }) => code);

export const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  admin: [...ALL_PERMISSION_CODES],
  teacher_main: [
    "student.view",
    "parent.view",
    "class.view",
    "schedule.view",
    "session.view",
    "session.manage",
    "attendance.view",
    "attendance.manage",
    "comment.view",
    "comment.manage",
    "exam.view",
    "exam.manage",
    "score.view",
    "score.manage",
    "report.learning.view",
  ],
  teacher_assistant: [
    "student.view",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
    "comment.view",
    "exam.view",
    "score.view",
  ],
  accountant: [
    "student.view",
    "parent.view",
    "class.view",
    "tuition.view",
    "tuition.manage",
    "payment.view",
    "payment.manage",
    "salary.view",
    "salary.manage",
    "report.finance.view",
    "report.staff.view",
  ],
  receptionist: [
    "student.view",
    "student.create",
    "student.update",
    "parent.view",
    "parent.create",
    "parent.update",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
  ],
  academic: [
    "student.view",
    "parent.view",
    "class.view",
    "class.create",
    "class.update",
    "class.assign_teacher",
    "schedule.view",
    "schedule.manage",
    "session.view",
    "session.manage",
    "attendance.view",
    "attendance.manage",
    "comment.view",
    "report.learning.view",
  ],
  collaborator: ["student.view", "class.view", "schedule.view", "session.view"],
  part_time: ["schedule.view", "session.view"],
  student: [
    "student.view",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
    "comment.view",
    "exam.view",
    "score.view",
  ],
  parent: [
    "student.view",
    "class.view",
    "schedule.view",
    "session.view",
    "attendance.view",
    "comment.view",
    "exam.view",
    "score.view",
    "tuition.view",
  ],
};

export function hasPermission(
  permissions: readonly string[],
  permission: PermissionCode,
) {
  return permissions.includes(permission);
}

export function roleLabel(code: string) {
  return ROLES.find((role) => role.code === code)?.name ?? code;
}
